### ISSUE TITLE
crashes when you open atom

### ISSUE THREAD

**Issue by stevenazari** [queenp/punchclock#1]
atoms default is to open without a project. as a result you get this:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: linux 3.13.0-46-generic
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the punchclock package

```
At undefined

- Timekeeper is active & functional only with a valid project open
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "followSymlinks": true
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.5.0
linter, v0.12.0
linter-php, v0.0.11
minimap, v4.6.0
punchclock, v0.5.0
wakatime, v4.0.1

# Dev
No dev packages
```

**Comment by queenp** [comment]
Cheers. I'll look into it.

**Comment by stevenazari** [comment]
Thanks for looking into it  :)

**Comment by queenp** [comment]
So sorry for how long this has taken, it should be fixed now (it no longer assumes there's a project open like before)
